export const D8_DX: readonly number[];
export const D8_DY: readonly number[];
export const RIVER_NONE: number;
export const RIVER_STREAM: number;
export const RIVER_TRIBUTARY: number;
export const RIVER_MAJOR: number;
export const RIVER_GREAT: number;
export function computeSeasonalRiverFlow(options: {
  readonly tw: number;
  readonly th: number;
  readonly tElev: ArrayLike<number>;
  readonly annualMoisture: ArrayLike<number>;
  readonly annualTemperature: ArrayLike<number>;
  readonly monthlyMoisture: ArrayLike<number>;
  readonly monthlyTemperature: ArrayLike<number>;
  readonly flowDir: ArrayLike<number>;
  readonly annualFlow: ArrayLike<number>;
  readonly drainsTerminal: ArrayLike<number>;
  readonly resolutionInvariantLoss?: boolean;
}): Float32Array;
