/**
 * Bake the crop wild-range descriptors to one or more grids.
 *
 * Usage:
 *   npx tsx tools/build-cropdata.mts [out.js] [width height]...
 *
 * The checked-in range descriptors remain the reviewable source. This tool is
 * intentionally deterministic and emits the same row-major base64 masks used
 * by the runtime sampler, so a refreshed biogeography bake cannot change the
 * mechanism.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import rangeData from "../data/reality/crop-ranges.json";

const output = process.argv[2];
if (!output) throw new Error("usage: build-cropdata.mts <out.js> [width height]...");
const dimensions = process.argv.slice(3).map(Number);
if (dimensions.length === 0 || dimensions.length % 2 !== 0) {
  throw new Error("provide width/height pairs for the baked grids");
}

function mask(width: number, height: number, boxes: readonly (readonly number[])[]): string {
  const result = new Uint8Array(width * height);
  for (const box of boxes) {
    const [minLon, maxLon, minLat, maxLat] = box;
    if ([minLon, maxLon, minLat, maxLat].some((value) => !Number.isFinite(value))) continue;
    for (let y = 0; y < height; y++) {
      const lat = 90 - ((y + 0.5) / height) * 180;
      if (lat < minLat! || lat > maxLat!) continue;
      for (let x = 0; x < width; x++) {
        const lon = ((x + 0.5) / width) * 360 - 180;
        if (lon >= minLon! && lon <= maxLon!) result[y * width + x] = 1;
      }
    }
  }
  return Buffer.from(result).toString("base64");
}

const baked: Record<string, Record<string, string>> = {};
for (let index = 0; index < dimensions.length; index += 2) {
  const width = dimensions[index]!;
  const height = dimensions[index + 1]!;
  const key = `${width}x${height}`;
  baked[key] = {};
  for (const range of rangeData.ranges) {
    baked[key][range.packageId] = mask(width, height, range.boxes);
  }
}

const source = readFileSync(
  fileURLToPath(new URL("../data/reality/crop-ranges.json", import.meta.url)),
  "utf8",
);
writeFileSync(
  output,
  `/* Generated by tools/build-cropdata.mts; source hash is supplied by the caller. */\n`
    + `export const CROP_RANGE_SOURCE = ${JSON.stringify(source)};\n`
    + `export const CROP_RANGE_GRIDS = ${JSON.stringify(baked)};\n`,
);
console.log(JSON.stringify({ output, grids: Object.keys(baked), packages: rangeData.ranges.length }));
