// GENERATED by tools/build_ipa_audio.mjs — do not edit by hand.
// 27 recorded phones (907 KB of audio in assets/ipa-audio/),
// covering 27/145 of the generator's base phone space.
// Per-file licence + author: assets/ipa-audio/SOURCES.tsv; see CREDITS-ipa-audio.md.
export const IPA_CLIP_CREDIT =
  "Phone recordings from Wikimedia Commons contributors (CC BY-SA / public domain per file — see CREDITS-ipa-audio.md)";
export const IPA_CLIPS = {"p":"0070.ogg","b":"0062.ogg","m":"006d.ogg","f":"0066.ogg","v":"0076.ogg","p͡f":"0070-0361-0066.ogg","b͡v":"0062-0361-0076.ogg","ʙ":"0299.ogg","w":"0077.ogg","t":"0074.ogg","d":"0064.ogg","n":"006e.ogg","s":"0073.ogg","z":"007a.ogg","t͡s":"0074-0361-0073.oga","d͡z":"0064-0361-007a.oga","l":"006c.ogg","r":"0072.ogg","ɹ":"0279.ogg","ʈ":"0288.oga","k":"006b.ogg","ʔ":"0294.ogg","y":"0079.ogg","e":"0065.ogg","ɛ":"025b.ogg","o":"006f.ogg","a":"0061.ogg"};
