// GENERATED by tools/build_ipa_audio.mjs — do not edit by hand.
// Placeholder (no fetch has run): the Lab hides the recorded-phones voice
// while the map is empty. Run the tool to populate assets/ipa-audio/ + this.
export const IPA_CLIP_CREDIT =
  "Phone recordings from Wikimedia Commons contributors (CC BY-SA / public domain per file — see CREDITS-ipa-audio.md)";
export const IPA_CLIPS = {};
