// GENERATED by tools/fit_tract_vowels.mjs — do not edit by hand.
// Calibrated vowel postures for the articulatory tract, fitted against the
// HUMAN formants measured from the recorded phone bank (assets/ipa-audio/
// formants.json ← tools/measure_vowel_truth.mjs). Keyed "height,backness,
// round,ATR"; each entry: tongueIndex, tongueDiameter, lip rounding, and the
// helper-constriction diameter (3 = none; a value < 3 pinches at the tongue
// position — how a real /u/ gets its low F2). Per-vowel ×k is the free
// vocal-tract-length normalization absorbed at fit time (the bank mixes
// speakers); it is NOT applied at synthesis.
// Mean weighted log-formant error vs truth: 38.918 (old mapping) → 0.059 (this table).
export const VOWEL_CAL = {
  "0,0,0,0": { ti: 29.5, td: 2.1, lip: 0.32, cd: 3 },  // [i] fit [270 3150 4020] ← human [230 2540 3410] ×1.1
  "0,0,0,1": { ti: 25, td: 2.1, lip: 0, cd: 3 },  // [ɪ] fit [330 2230] ← human [400 2080 2940] ×0.95
  "0,0,1,0": { ti: 28, td: 3.5, lip: 0.58, cd: 0.5 },  // [y] fit [270 1730 2160] ← human [230 1990 2390] ×0.98
  "0,0,1,1": { ti: 13, td: 3.3, lip: 0.83, cd: 0.5 },  // [ʏ] fit [370 1470] ← human [370 1580 2150] ×0.96
  "0,1,0,1": { ti: 16, td: 3.3, lip: 0, cd: 0.9 },  // [ɪ̈] fit [390 890 2010] ← human [380 1460 2640] ×0.85
  "0,1,1,0": { ti: 13, td: 3.3, lip: 1, cd: 0.5 },  // [ʉ] fit [320 1480] ← human [230 1200 2330] ×0.98
  "0,2,0,0": { ti: 16, td: 3.5, lip: 0, cd: 0.7 },  // [ɯ] fit [370 840 2080] ← human [320 1080 2750] ×0.95
  "0,2,0,1": { ti: 16, td: 3.3, lip: 0, cd: 0.9 },  // [ɯ̽] fit [390 890 2010] ← human [440 1350 2490] ×0.85
  "0,2,1,0": { ti: 26.5, td: 3.1, lip: 0.57, cd: 0.9 },  // [u] fit [300 620 2030] ← human [250 620 1670] ×0.98
  "0,2,1,1": { ti: 8.5, td: 3.1, lip: 0.33, cd: 0.7 },  // [ʊ] fit [410 800 2160] ← human [430 1010 2630] ×0.95
  "1,0,0,0": { ti: 29.5, td: 2.7, lip: 0.12, cd: 3 },  // [e] fit [320 2700 3750] ← human [340 2830 3900] ×0.95
  "1,0,0,1": { ti: 13, td: 3.3, lip: 0, cd: 0.5 },  // [ɛ] fit [470 910] ← human [580 1910 2710] ×0.78
  "1,0,1,0": { ti: 13, td: 3.3, lip: 0.95, cd: 0.5 },  // [ø] fit [330 1480] ← human [330 1500 2290] ×0.99
  "1,0,1,1": { ti: 13, td: 3.3, lip: 0.83, cd: 0.5 },  // [œ] fit [370 1470] ← human [540 1480 2450] ×0.95
  "1,1,0,0": { ti: 8.5, td: 2.9, lip: 0, cd: 0.5 },  // [ə] fit [460 890 2180] ← human [510 1200 2560] ×0.95
  "1,1,0,1": { ti: 8.5, td: 2.7, lip: 0, cd: 0.5 },  // [ɜ] fit [480 890 2090] ← human [630 1490 2570] ×0.78
  "1,1,1,0": { ti: 10, td: 3.3, lip: 0.45, cd: 0.5 },  // [ɵ] fit [370 760 2100] ← human [420 850 2410] ×0.89
  "1,1,1,1": { ti: 13, td: 3.3, lip: 0.33, cd: 0.5 },  // [ɞ] fit [440 840] ← human [500 1010 3190] ×0.86
  "1,2,0,0": { ti: 16, td: 3.3, lip: 0, cd: 0.9 },  // [ɤ] fit [390 890 2010] ← human [390 1340 2600] ×0.95
  "1,2,0,1": { ti: 8.5, td: 2.7, lip: 0, cd: 0.9 },  // [ʌ] fit [500 880 2140] ← human [660 1240 2530] ×0.78
  "1,2,1,0": { ti: 8.5, td: 3.3, lip: 0.45, cd: 3 },  // [o] fit [390 720 2130] ← human [360 550 1840] ×1.1
  "1,2,1,1": { ti: 8.5, td: 1.9, lip: 0.57, cd: 3 },  // [ɔ] fit [460 660 3650] ← human [560 727] ×0.86
  "2,0,0,0": { ti: 8.5, td: 2.7, lip: 0.12, cd: 3 },  // [æ] fit [850 2150 3840] ← human [810 1760 2600] ×0.98
  "2,0,1,0": { ti: 11.5, td: 3.1, lip: 0.33, cd: 0.9 },  // [ɶ] fit [410 810 1960] ← human [560 1200 2300] ×0.78
  "2,2,0,0": { ti: 8.5, td: 2.7, lip: 0, cd: 0.9 },  // [ɑ] fit [500 880 2140] ← human [640 990 2400] ×0.84
  "2,2,1,0": { ti: 8.5, td: 1.9, lip: 0.57, cd: 3 },  // [ɒ] fit [460 660 3650] ← human [560 727] ×0.86
};
