// GENERATED by tools/fit_tract_vowels.mjs — do not edit by hand.
// Placeholder (no fit has run): vowelPosture falls back to its analytic
// posture formula until the fitted table replaces this file.
export const VOWEL_CAL = {};
