// GENERATED by tools/fit_tract_vowels.mjs — do not edit by hand.
// Calibrated vowel postures for the articulatory tract, fitted against the
// HUMAN formants measured from the recorded phone bank (assets/ipa-audio/
// formants.json ← tools/measure_vowel_truth.mjs). Keyed "height,backness,
// round,ATR"; each entry: tongueIndex, tongueDiameter, lip rounding, and the
// helper-constriction diameter (3 = none; a value < 3 pinches at the tongue
// position — how a real /u/ gets its low F2). Per-vowel ×k is the free
// vocal-tract-length normalization absorbed at fit time (the bank mixes
// speakers); it is NOT applied at synthesis.
// Mean weighted log-formant error vs truth: 0.366 (old mapping) → 0.062 (this table).
export const VOWEL_CAL = {
  "0,0,0,0": { ti: 28, td: 2.1, lip: 0, cd: 3 },  // [i] fit [280 2910 3950] ← human [230 2540 3410] ×1.1
  "0,0,0,1": { ti: 25, td: 2.5, lip: 0, cd: 3 },  // [ɪ] fit [340 2110 3560] ← human [400 2080 2940] ×0.97
  "0,0,1,0": { ti: 28, td: 3.5, lip: 0.7, cd: 0.5 },  // [y] fit [260 1880 3280] ← human [230 1990 2390] ×0.98
  "0,0,1,1": { ti: 13, td: 3.5, lip: 0.83, cd: 0.5 },  // [ʏ] fit [360 1480] ← human [370 1580 2150] ×0.95
  "0,1,0,1": { ti: 25, td: 2.5, lip: 0, cd: 0.5 },  // [ɪ̈] fit [340 2080 3590] ← human [380 1460 2640] ×1.05
  "0,1,1,0": { ti: 13, td: 3.1, lip: 1, cd: 0.5 },  // [ʉ] fit [310 1360 2780] ← human [230 1200 2330] ×0.98
  "0,2,0,0": { ti: 16, td: 3.3, lip: 0, cd: 0.5 },  // [ɯ] fit [360 800 3310] ← human [320 1080 2750] ×0.95
  "0,2,0,1": { ti: 14.5, td: 3.3, lip: 0, cd: 3 },  // [ɯ̽] fit [410 830 1930] ← human [440 1350 2490] ×0.85
  "0,2,1,0": { ti: 10, td: 3.5, lip: 0.7, cd: 0.5 },  // [u] fit [310 610 1920] ← human [250 620 1670] ×0.98
  "0,2,1,1": { ti: 17.5, td: 2.7, lip: 0.33, cd: 0.5 },  // [ʊ] fit [390 800 3440] ← human [430 1010 2630] ×0.95
  "1,0,0,0": { ti: 28, td: 2.3, lip: 0, cd: 0.5 },  // [e] fit [320 2630 3690] ← human [340 2830 3900] ×0.95
  "1,0,0,1": { ti: 8.5, td: 2.7, lip: 0.12, cd: 3 },  // [ɛ] fit [790 2000 3540] ← human [580 1910 2710] ×0.98
  "1,0,1,0": { ti: 13, td: 3.5, lip: 0.83, cd: 0.7 },  // [ø] fit [340 1540] ← human [330 1500 2290] ×1.03
  "1,0,1,1": { ti: 13, td: 3.5, lip: 0.83, cd: 0.5 },  // [œ] fit [360 1480] ← human [540 1480 2450] ×0.95
  "1,1,0,0": { ti: 11.5, td: 3.3, lip: 0, cd: 0.5 },  // [ə] fit [440 850] ← human [510 1200 2560] ×0.95
  "1,1,0,1": { ti: 11.5, td: 3.3, lip: 0, cd: 0.5 },  // [ɜ] fit [440 850] ← human [630 1490 2570] ×0.78
  "1,1,1,0": { ti: 8.5, td: 3.1, lip: 0.45, cd: 3 },  // [ɵ] fit [340 690 1960] ← human [420 850 2410] ×0.81
  "1,1,1,1": { ti: 13, td: 3.1, lip: 0.33, cd: 0.5 },  // [ɞ] fit [460 780] ← human [500 1010 3190] ×0.85
  "1,2,0,0": { ti: 25, td: 2.5, lip: 0, cd: 0.5 },  // [ɤ] fit [340 2080 3590] ← human [390 1340 2600] ×1.1
  "1,2,0,1": { ti: 10, td: 3.1, lip: 0, cd: 3 },  // [ʌ] fit [480 830 2010] ← human [660 1240 2530] ×0.78
  "1,2,1,0": { ti: 8.5, td: 3.1, lip: 0.7, cd: 0.9 },  // [o] fit [320 600 1880] ← human [360 550 1840] ×0.99
  "1,2,1,1": { ti: 8.5, td: 2.3, lip: 0.45, cd: 0.9 },  // [ɔ] fit [460 680 3430] ← human [560 727] ×0.88
  "2,0,0,0": { ti: 10, td: 2.9, lip: 0, cd: 3 },  // [æ] fit [830 1960 3530] ← human [810 1760 2600] ×0.98
  "2,0,1,0": { ti: 11.5, td: 3.3, lip: 0.33, cd: 0.5 },  // [ɶ] fit [410 760] ← human [560 1200 2300] ×0.78
  "2,2,0,0": { ti: 10, td: 3.1, lip: 0, cd: 3 },  // [ɑ] fit [480 830 2010] ← human [640 990 2400] ×0.8
  "2,2,1,0": { ti: 8.5, td: 2.3, lip: 0.45, cd: 0.9 },  // [ɒ] fit [460 680 3430] ← human [560 727] ×0.88
};
