// Bake the measured HUMAN vowel formants (assets/ipa-audio/formants.json ←
// tools/measure_vowel_truth.mjs) into a table for the Lab's FORMANT voice.
// A formant synthesizer takes formants as INPUT, so calibration is direct:
// no fitting loop, no articulatory search — the measured values, normalized
// to one male speaker frame, become the resonator targets.
//
//   node tools/bake_formant_vowels.mjs        # → src/sim/formantVowelCal.js
//
// Normalization: the bank mixes speakers of different vocal-tract lengths.
// Each entry is scaled toward a ~105–120 Hz male frame by the midpoint of
// the same F0-anchored VTL window the tract fitter uses (high-pitched
// recordings shrink, male-pitched pass near-unchanged), so the table is one
// coherent voice rather than a choir. Entries the plausibility screen
// flagged are skipped (the synth's analytic formula covers them).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const truth = JSON.parse(readFileSync(join(ROOT, "assets", "ipa-audio", "formants.json"), "utf8"));
const kMid = (f0) => (f0 >= 180 ? 0.88 : f0 >= 140 ? 0.95 : 1.02);

// round-back merged-F2 repair, same as the tract fitter: F1 is valid, F2 is
// the merge artifact — take it from the round-back peers and re-admit
for (const [sym, t] of Object.entries(truth)) {
  if (t.b === 2 && t.r === 1 && t.F.length >= 2 && t.F[1] > 1800) {
    const peers = Object.values(truth).filter(u => u.b === 2 && u.r === 1 && u.F.length >= 2 && u.F[1] <= 1800);
    if (peers.length) {
      t.F = [t.F[0], Math.round(peers.reduce((a, u) => a + u.F[1], 0) / peers.length)];
      delete t.suspect;
      console.log(`(repaired [${sym}] F2 from round-back peers)`);
    }
  }
}

const rows = [];
let skipped = 0;
for (const [sym, t] of Object.entries(truth)) {
  if (t.suspect || t.F.length < 2) { skipped++; continue; }
  const k = kMid(t.f0);
  const F = t.F.map(f => Math.round(f * k));
  if (F.length < 3) F.push(t.r ? 2500 : 2700);            // F3 unmeasured → analytic default
  rows.push({ key: `${t.h},${t.b},${t.r},${t.atr}`, F: F.slice(0, 3), sym, f0: t.f0, k });
}
rows.sort((a, b) => (a.key < b.key ? -1 : 1));

const lines = rows.map(r => `  "${r.key}": [${r.F.join(", ")}],  // [${r.sym}] ×${r.k} (F0 ${r.f0})`);
const mod = `// GENERATED by tools/bake_formant_vowels.mjs — do not edit by hand.
// Vowel formant targets for the Lab's formant voice, measured from the
// recorded phone bank (assets/ipa-audio) and VTL-normalized to one male
// speaker frame. Keyed "height,backness,round,ATR" → [F1, F2, F3] Hz.
// ${rows.length} measured qualities${skipped ? ` (${skipped} skipped by the plausibility screen — analytic fallback)` : ""}.
export const FORMANT_VOWELS = {
${lines.join("\n")}
};
`;
writeFileSync(join(ROOT, "src", "sim", "formantVowelCal.js"), mod);
console.log(`wrote src/sim/formantVowelCal.js (${rows.length} vowels, ${skipped} skipped)`);
