import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
const __dirname = dirname(fileURLToPath(import.meta.url));
const src = readFileSync(join(__dirname, '../src/WorldSim.jsx'), 'utf-8');
const startIdx = src.indexOf('const PERM=');
const endIdx = src.indexOf('export default function WorldSim');
const pureCode = src.substring(startIdx, endIdx);
const { computeRivers, RIVER_NONE, RIVER_STREAM, RIVER_TRIBUTARY, RIVER_MAJOR, RIVER_GREAT } = await import('../src/riverGen.js');
const { generateResources, tileResourceSummary, dominantResource, RESOURCES, RES_BY_ID } = await import('../src/resourceGen.js');
const { EARTH_ELEV, EARTH_W, EARTH_H, decodeEarth, sampleEarth } = await import('../src/earthData.js');
const { solveWind } = await import('../src/windSolver.js');
const { solveMoisture } = await import('../src/moistureSolver.js');
const RIVER_NAMES=['','Stream','Tributary','Major River','Great River'];
const generateTectonicWorld=()=>null;const isRealWindAvailable=()=>false;const fillRealWind=()=>{};
const fnBody=`const RIVER_NAMES=${JSON.stringify(RIVER_NAMES)};const RIVER_NONE=${RIVER_NONE};const RIVER_STREAM=${RIVER_STREAM};const RIVER_TRIBUTARY=${RIVER_TRIBUTARY};const RIVER_MAJOR=${RIVER_MAJOR};const RIVER_GREAT=${RIVER_GREAT};${pureCode}return{generateWorld,createTerritory};`;
const factory=new Function('computeRivers','generateResources','tileResourceSummary','dominantResource','RESOURCES','RES_BY_ID','generateTectonicWorld','solveWind','solveMoisture','EARTH_ELEV','EARTH_W','EARTH_H','decodeEarth','sampleEarth','isRealWindAvailable','fillRealWind',fnBody);
const fns=factory(computeRivers,generateResources,tileResourceSummary,dominantResource,RESOURCES,RES_BY_ID,generateTectonicWorld,solveWind,solveMoisture,EARTH_ELEV,EARTH_W,EARTH_H,decodeEarth,sampleEarth,isRealWindAvailable,fillRealWind);
const world=fns.generateWorld(1920,960,1234,'earth_sim',0.78);
const ter=fns.createTerritory(world);
let total=0,veryLow=0,low=0,mod=0,high=0;
let cold=0,highDiff=0;
for(let ti=0;ti<ter.tw*ter.th;ti++){
  if(ter.tElev[ti]<=0)continue;total++;
  const f=ter.tFert[ti],d=ter.tDiff[ti],t=ter.tTemp[ti];
  if(f<0.02)veryLow++;
  else if(f<0.1)low++;
  else if(f<0.3)mod++;
  else high++;
  if(t<0.15)cold++;
  if(d>0.5)highDiff++;
}
console.log(`Total land: ${total}`);
console.log(`  fert<0.02 (barren):     ${veryLow} (${(veryLow/total*100).toFixed(1)}%)`);
console.log(`  fert 0.02-0.10 (poor):  ${low} (${(low/total*100).toFixed(1)}%)`);
console.log(`  fert 0.10-0.30 (mod):   ${mod} (${(mod/total*100).toFixed(1)}%)`);
console.log(`  fert>0.30 (good):       ${high} (${(high/total*100).toFixed(1)}%)`);
console.log(`  temp<0.15 (cold):       ${cold} (${(cold/total*100).toFixed(1)}%)`);
console.log(`  diff>0.5 (very hard):   ${highDiff} (${(highDiff/total*100).toFixed(1)}%)`);
console.log(`\nExpected max coverage: ~${((total-veryLow)/total*100).toFixed(0)}% (excluding barren)`);
console.log(`Realistic max: ~${((total-veryLow-cold*0.3)/total*100).toFixed(0)}% (excluding barren + most cold)`);
